/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Farms;
import static sql.Sql.*;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.derby.shared.common.error.DerbySQLIntegrityConstraintViolationException;



/**
 *
 * @author Mohammed
 */

public class LoginFrm extends javax.swing.JFrame {

    /**
     * Creates new form testFrm
     */
    public LoginFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        WindowSignIn = new javax.swing.JPanel();
        PanExit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IconUserName = new javax.swing.JLabel();
        LineUserName = new javax.swing.JSeparator();
        IconSingIn = new javax.swing.JLabel();
        IconPassword = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        LinePassword = new javax.swing.JSeparator();
        SignIn = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblDesgin = new javax.swing.JLabel();
        lblLoginIn = new javax.swing.JLabel();
        lblBackgroundLoginIn = new javax.swing.JLabel();
        lblIDont = new javax.swing.JLabel();
        WindowLooding = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        SignUp = new javax.swing.JPanel();
        SignIn2 = new javax.swing.JLabel();
        IconSingIn1 = new javax.swing.JLabel();
        panreturn = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        PanExit1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        LinePassword1 = new javax.swing.JSeparator();
        txtPassword1 = new javax.swing.JTextField();
        LineUserName1 = new javax.swing.JSeparator();
        txtUserName1 = new javax.swing.JTextField();
        IconUserName1 = new javax.swing.JLabel();
        lblSignUp = new javax.swing.JLabel();
        lblBackgroundLoginIn1 = new javax.swing.JLabel();
        IconPassword2 = new javax.swing.JLabel();
        LineStationName = new javax.swing.JSeparator();
        txtStationName = new javax.swing.JTextField();
        IconStationName = new javax.swing.JLabel();

        setTitle("Login In");
        setUndecorated(true);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new java.awt.CardLayout());

        WindowSignIn.setBackground(new java.awt.Color(255, 255, 255));
        WindowSignIn.setEnabled(false);
        WindowSignIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanExit.setBackground(new java.awt.Color(169, 221, 233));
        PanExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanExitMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setText(" x");

        javax.swing.GroupLayout PanExitLayout = new javax.swing.GroupLayout(PanExit);
        PanExit.setLayout(PanExitLayout);
        PanExitLayout.setHorizontalGroup(
            PanExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanExitLayout.setVerticalGroup(
            PanExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        WindowSignIn.add(PanExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 60, -1));

        IconUserName.setFont(new java.awt.Font("Swis721 BlkRnd BT", 0, 24)); // NOI18N
        WindowSignIn.add(IconUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 50, 44));

        LineUserName.setBackground(new java.awt.Color(170, 222, 233));
        WindowSignIn.add(LineUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 261, 40));
        WindowSignIn.add(IconSingIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 90, 80));

        IconPassword.setFont(new java.awt.Font("Swis721 BlkRnd BT", 0, 24)); // NOI18N
        WindowSignIn.add(IconPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        txtUserName.setFont(new java.awt.Font("29LT Bukra Regular", 0, 18)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(153, 153, 153));
        txtUserName.setText("User Name");
        txtUserName.setBorder(null);
        txtUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        txtUserName.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        txtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserNameFocusGained(evt);
            }
        });
        WindowSignIn.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 261, 27));

        LinePassword.setBackground(new java.awt.Color(170, 222, 233));
        WindowSignIn.add(LinePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 257, 10));

        SignIn.setFont(new java.awt.Font("Arista Pro Alternate", 0, 36)); // NOI18N
        SignIn.setText("Sign In");
        WindowSignIn.add(SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 100, 120));

        txtPassword.setFont(new java.awt.Font("29LT Bukra Regular", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setText("Password");
        txtPassword.setBorder(null);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
        });
        WindowSignIn.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 257, 27));
        WindowSignIn.add(lblDesgin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 540, 280));

        lblLoginIn.setBackground(new java.awt.Color(255, 255, 255));
        lblLoginIn.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 24)); // NOI18N
        lblLoginIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginIn.setText("login In");
        lblLoginIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoginInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLoginInMouseExited(evt);
            }
        });
        WindowSignIn.add(lblLoginIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 240, 40));

        lblBackgroundLoginIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackgroundLoginInMouseEntered(evt);
            }
        });
        WindowSignIn.add(lblBackgroundLoginIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, -1, -1));

        lblIDont.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblIDont.setForeground(new java.awt.Color(255, 0, 51));
        lblIDont.setText("I don't have account ");
        lblIDont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIDontMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIDontMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIDontMouseExited(evt);
            }
        });
        WindowSignIn.add(lblIDont, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 650, -1, -1));

        jPanel6.add(WindowSignIn, "card2");

        WindowLooding.setBackground(new java.awt.Color(255, 255, 255));
        WindowLooding.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        WindowLooding.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 200, 240));

        jLabel10.setFont(new java.awt.Font("29LT Bukra Bold", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(88, 187, 208));
        jLabel10.setText("Please Looding....");
        WindowLooding.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 270, 40));

        jPanel4.setBackground(new java.awt.Color(170, 222, 233));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel11.setText(" x");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        WindowLooding.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 60, -1));
        WindowLooding.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 540, 250));

        jPanel6.add(WindowLooding, "card3");

        SignUp.setBackground(new java.awt.Color(255, 255, 255));
        SignUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignIn2.setFont(new java.awt.Font("Arista Pro Alternate", 0, 36)); // NOI18N
        SignIn2.setText("Sign Up");
        SignUp.add(SignIn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 120, 120));
        SignUp.add(IconSingIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 90, 80));

        panreturn.setBackground(new java.awt.Color(169, 221, 233));
        panreturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panreturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panreturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panreturnMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 50)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panreturnLayout = new javax.swing.GroupLayout(panreturn);
        panreturn.setLayout(panreturnLayout);
        panreturnLayout.setHorizontalGroup(
            panreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(panreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panreturnLayout.createSequentialGroup()
                    .addContainerGap(17, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );
        panreturnLayout.setVerticalGroup(
            panreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(panreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        SignUp.add(panreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        PanExit1.setBackground(new java.awt.Color(169, 221, 233));
        PanExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanExit1MouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel3.setText(" x");

        javax.swing.GroupLayout PanExit1Layout = new javax.swing.GroupLayout(PanExit1);
        PanExit1.setLayout(PanExit1Layout);
        PanExit1Layout.setHorizontalGroup(
            PanExit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanExit1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanExit1Layout.setVerticalGroup(
            PanExit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        SignUp.add(PanExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 60, -1));
        SignUp.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 890, 280));

        LinePassword1.setBackground(new java.awt.Color(170, 222, 233));
        SignUp.add(LinePassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 257, 10));

        txtPassword1.setFont(new java.awt.Font("29LT Bukra Regular", 0, 18)); // NOI18N
        txtPassword1.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword1.setText("Password");
        txtPassword1.setBorder(null);
        txtPassword1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassword1FocusGained(evt);
            }
        });
        SignUp.add(txtPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 257, 27));

        LineUserName1.setBackground(new java.awt.Color(170, 222, 233));
        SignUp.add(LineUserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 261, 40));

        txtUserName1.setFont(new java.awt.Font("29LT Bukra Regular", 0, 18)); // NOI18N
        txtUserName1.setForeground(new java.awt.Color(153, 153, 153));
        txtUserName1.setText("User Name");
        txtUserName1.setBorder(null);
        txtUserName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserName1FocusGained(evt);
            }
        });
        SignUp.add(txtUserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 261, 27));

        IconUserName1.setFont(new java.awt.Font("Swis721 BlkRnd BT", 0, 24)); // NOI18N
        SignUp.add(IconUserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 50, 44));

        lblSignUp.setBackground(new java.awt.Color(255, 255, 255));
        lblSignUp.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 24)); // NOI18N
        lblSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSignUp.setText("Sing Up");
        lblSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSignUpMouseExited(evt);
            }
        });
        SignUp.add(lblSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 240, 40));
        SignUp.add(lblBackgroundLoginIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, -1, -1));

        IconPassword2.setFont(new java.awt.Font("Swis721 BlkRnd BT", 0, 24)); // NOI18N
        SignUp.add(IconPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        LineStationName.setBackground(new java.awt.Color(170, 222, 233));
        SignUp.add(LineStationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 257, 10));

        txtStationName.setFont(new java.awt.Font("29LT Bukra Regular", 0, 18)); // NOI18N
        txtStationName.setForeground(new java.awt.Color(153, 153, 153));
        txtStationName.setText("Company Name");
        txtStationName.setBorder(null);
        txtStationName.setDragEnabled(true);
        txtStationName.setInheritsPopupMenu(true);
        txtStationName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtStationNameFocusGained(evt);
            }
        });
        SignUp.add(txtStationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 257, 27));

        IconStationName.setFont(new java.awt.Font("Swis721 BlkRnd BT", 0, 24)); // NOI18N
        SignUp.add(IconStationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jPanel6.add(SignUp, "card4");

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int x=170,y=222,z=233;
    private void PanExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanExitMouseEntered
//        try {
//         
//            PanExit.setBackground(new Color(200,150,150));    
//            Thread.sleep(100);
//            PanExit.setBackground(new Color(200,100,100));    
//            Thread.sleep(100);
//            PanExit.setBackground(new Color(230,51,51));    
//            
//            
//        } catch (InterruptedException ex) {
//            Logger.getLogger(LoginFrm.class.getName()).log(Level.SEVERE, null, ex);
//        }
          PanExit.setBackground(new Color(240,39,39));    
          jLabel1.setForeground(Color.white);
    }//GEN-LAST:event_PanExitMouseEntered

    private void PanExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanExitMouseExited
        PanExit.setBackground(new Color(170,222,233));
        jLabel1.setForeground(Color.black);
    }//GEN-LAST:event_PanExitMouseExited

    private void PanExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanExitMouseClicked
      System.exit(0);
    }//GEN-LAST:event_PanExitMouseClicked

    private void txtUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusGained
        txtUserName.setText("");
        txtUserName.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtUserNameFocusGained

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
             txtPassword.setText("");
  txtPassword.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtPasswordFocusGained
    public  static Object id_company;
    
    private void lblLoginInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginInMouseClicked

        WindowLooding.setVisible(true);
       WindowSignIn.setVisible(false);
   
          id_company = sql.Sql.selectRow("select id_company from company where user_name='"+txtUserName.getText().toLowerCase()+"' and password='"+txtPassword.getText().toLowerCase()+"'");
        if (id_company!=null) { //JOptionPane.showMessageDialog(null, "Connected succussfuly","Successe",JOptionPane.INFORMATION_MESSAGE);
            AdminFrm l= new AdminFrm();
            l.setLocationRelativeTo(null);
            l.setVisible(true);
            this.dispose();}
        else if (txtUserName.getText().equalsIgnoreCase("user")&&txtPassword.getText().equalsIgnoreCase("user")) {
            try {
                UserFrm l= new UserFrm();
                l.setLocationRelativeTo(null);
                l.setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(LoginFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            txtUserName.setForeground(new Color(153,153,153));
            txtUserName.setText("User Name");
            txtPassword.setForeground(new Color(153,153,153));
            txtPassword.setText("Password");
            JOptionPane.showMessageDialog(null, "user name or password inccorect");}
        WindowSignIn.show();
        WindowLooding.hide();
        
    }//GEN-LAST:event_lblLoginInMouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
      System.exit(0);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
       jPanel4.setBackground(Color.red);
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
       jPanel4.setBackground(Color.white);
    }//GEN-LAST:event_jPanel4MouseExited

    private void lblBackgroundLoginInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundLoginInMouseEntered
//       jLabel7.setBackground(new Color(170,222,233).darker());
    }//GEN-LAST:event_lblBackgroundLoginInMouseEntered

    private void lblLoginInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginInMouseEntered
        lblLoginIn.setForeground(new Color(170,222,233).darker());
    }//GEN-LAST:event_lblLoginInMouseEntered

    private void lblLoginInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginInMouseExited
    lblLoginIn.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblLoginInMouseExited

    private void txtPassword1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassword1FocusGained
       txtPassword1.setText("");
       txtPassword1.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtPassword1FocusGained

    private void txtUserName1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserName1FocusGained
       txtUserName1.setText("");
       txtUserName1.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtUserName1FocusGained

    private void lblSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignUpMouseClicked
//        System.out.println(txtPassword1.getForeground().getRed());
        if (txtPassword1.getText().length()!=0&&txtPassword1.getForeground().getRed()!=153) {
            try {
                setconnection();
                Statement s = co.createStatement();
//                s.("");
                AdminFrm a=   new AdminFrm();
                a.setLocationRelativeTo(null);
                this.dispose();
                a.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(LoginFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_lblSignUpMouseClicked

    private void lblSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignUpMouseEntered
      lblSignUp.setForeground(new Color(170,222,233).darker());
    }//GEN-LAST:event_lblSignUpMouseEntered

    private void lblSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignUpMouseExited
      
         lblSignUp.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblSignUpMouseExited

    private void txtStationNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStationNameFocusGained
       txtStationName.setForeground(Color.BLACK);
        txtStationName.setText("");
    }//GEN-LAST:event_txtStationNameFocusGained

    private void lblIDontMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIDontMouseEntered
    
        lblIDont.setForeground(Color.RED.darker());
    }//GEN-LAST:event_lblIDontMouseEntered

    private void lblIDontMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIDontMouseClicked
        txtUserName.setForeground(new Color(153,153,153));
        txtUserName.setText("User Name");
        txtPassword.setForeground(new Color(153,153,153));
        txtPassword.setText("Password");
        WindowSignIn.hide();
        SignUp.show();
    }//GEN-LAST:event_lblIDontMouseClicked

    private void lblIDontMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIDontMouseExited
       lblIDont.setForeground(new Color(255,0,51));
    }//GEN-LAST:event_lblIDontMouseExited

    private void PanExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanExit1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_PanExit1MouseClicked

    private void PanExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanExit1MouseEntered
      PanExit1.setBackground(Color.red);
      jLabel3.setForeground(Color.white);
    }//GEN-LAST:event_PanExit1MouseEntered

    private void PanExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanExit1MouseExited
        PanExit1.setBackground(new Color(169,221,233));
      jLabel3.setForeground(Color.BLACK);
    }//GEN-LAST:event_PanExit1MouseExited

    private void panreturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panreturnMouseExited
        panreturn.setBackground(new Color(170,222,233));
        jLabel8.setForeground(Color.black);
    }//GEN-LAST:event_panreturnMouseExited

    private void panreturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panreturnMouseEntered
        panreturn.setBackground(new Color(0,222,230));
        jLabel8.setForeground(Color.white);
    }//GEN-LAST:event_panreturnMouseEntered

    private void panreturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panreturnMouseClicked
        SignUp.hide();
        txtStationName.setForeground(new Color(153,153,153));
        txtStationName.setText("Company Name");
        txtUserName1.setForeground(new Color(153,153,153));
        txtUserName1.setText("User Name");
        txtPassword1.setForeground(new Color(153,153,153));
        txtPassword1.setText("Password");
        WindowSignIn.show();
    }//GEN-LAST:event_panreturnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconPassword;
    private javax.swing.JLabel IconPassword2;
    private javax.swing.JLabel IconSingIn;
    private javax.swing.JLabel IconSingIn1;
    private javax.swing.JLabel IconStationName;
    private javax.swing.JLabel IconUserName;
    private javax.swing.JLabel IconUserName1;
    private javax.swing.JSeparator LinePassword;
    private javax.swing.JSeparator LinePassword1;
    private javax.swing.JSeparator LineStationName;
    private javax.swing.JSeparator LineUserName;
    private javax.swing.JSeparator LineUserName1;
    private javax.swing.JPanel PanExit;
    private javax.swing.JPanel PanExit1;
    private javax.swing.JLabel SignIn;
    private javax.swing.JLabel SignIn2;
    private javax.swing.JPanel SignUp;
    private javax.swing.JPanel WindowLooding;
    private javax.swing.JPanel WindowSignIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblBackgroundLoginIn;
    private javax.swing.JLabel lblBackgroundLoginIn1;
    private javax.swing.JLabel lblDesgin;
    private javax.swing.JLabel lblIDont;
    private javax.swing.JLabel lblLoginIn;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JPanel panreturn;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPassword1;
    private javax.swing.JTextField txtStationName;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtUserName1;
    // End of variables declaration//GEN-END:variables
}
